server:
  port: 9095   # compose’ta 9095:9095 ise böyle kalsın

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/paystream?currentSchema=payment
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: payment    # ek garanti

  flyway:
    enabled: true
    locations: classpath:db/migration   # /src/main/resources/db/migration
    schemas: payment
    default-schema: payment
    create-schemas: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

redis:
  host: redis
  port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
