spring:
  application:
    name: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


payment:
  risk:
    threeDs-enabled: true
    amount-threshold: 1000.00

