CREATE USER debezium WITH REPLICATION LOGIN PASSWORD 'dbz';
GRANT CONNECT ON DATABASE paystream TO debezium;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO debezium;
