server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account
          uri: lb://account-service
          predicates:
            - Path=/accounts/**    # <--- BURASI
          # filters:
          #   - StripPrefix=0      # (gerek yok)
