server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          # filters:
          #   - StripPrefix=0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: account-service
        url: /account/v3/api-docs
      - name: ledger-service
        url: /ledger/v3/api-docs
      - name: transfer-service
        url: /transfer/v3/api-docs
