version: "3.9"
name: paystream-dev

# -----------------------------
# Networks
# -----------------------------
networks:
  paystream-net:

# -----------------------------
# Services
# -----------------------------
services:
  # ---------- Infra ----------
  postgres:
    image: postgres:16
    container_name: ps-postgres
    command: >
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-paystream}
    ports:
      - "5433:5432"
    volumes:
      # Debezium kullanıcısı ve yetkileri için init scriptler
      - ./initdb:/docker-entrypoint-initdb.d
      # (opsiyonel) kalıcı veri:
      # - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [paystream-net]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: ps-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks: [paystream-net]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: ps-kafka
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # İç/dış listener'lar (container içi: kafka:9092, host: localhost:29092)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [paystream-net]

  connect:
    image: debezium/connect:2.6
    container_name: ps-connect
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: _connect_configs
      OFFSET_STORAGE_TOPIC: _connect_offsets
      STATUS_STORAGE_TOPIC: _connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    ports:
      - "8083:8083"
    networks: [paystream-net]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ps-kafka-ui
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks: [paystream-net]

  redis:
    image: redis:7
    container_name: ps-redis
    ports:
      - "6379:6379"
    networks: [paystream-net]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: ps-keycloak
    command: ["start-dev", "--http-port=8081"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "8081:8081"
    networks: [paystream-net]

  weaviate:
    image: semitechnologies/weaviate:1.24.10
    container_name: ps-weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    ports:
      - "8082:8080"
    networks: [paystream-net]

  # ---------- Platform Apps ----------
  service-registry:
    container_name: ps-eureka
    build:
      context: ../platform/service-registry
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    depends_on: []
    networks: [paystream-net]

  api-gateway:
    container_name: ps-gateway
    build:
      context: ../platform/api-gateway
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_URL: http://service-registry:8761/eureka
    ports:
      - "8084:8080"   # host:8084 → gateway (istersen 8080'ı da kullanabilirsin)
    depends_on:
      service-registry:
        condition: service_started
      account-service:
        condition: service_started
    networks: [paystream-net]

  # ---------- Core Apps ----------
  account-service:
    container_name: ps-account
    build:
      context: ../core/account-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Docker profili yerine env kullanacaksan alttakileri aç:
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paystream
      # SPRING_DATASOURCE_USERNAME: postgres
      # SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_URL: http://service-registry:8761/eureka
      SERVER_PORT: 9000
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
      service-registry:
        condition: service_started
    networks: [paystream-net]
