server:
  port: 9100

spring:
  application:
    name: ledger-service
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: INFO

ledger:
  outbox.relay.enabled: true
  snapshot.consumer.enabled: true
