server:
  port: 9100

spring:
  application:
    name: ledger-service
  datasource:
    url: ${LEDGER_DB_URL:jdbc:postgresql://localhost:5434/ledgerdb}
    username: ${LEDGER_DB_USER:postgres}
    password: ${LEDGER_DB_PASS:postgres}
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: INFO
