server:
  port: 9100   # compose ile eşlendi

spring:
  application:
    name: ledger-service
  datasource:
    url: jdbc:postgresql://postgres:5432/paystream
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
