server:
  port: 9000

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://postgres:5432/paystream
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  main:
    web-application-type: servlet

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
