server:
  port: 9000

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/paystream
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  main:
    web-application-type: servlet

eureka:
  client:
    enabled: false

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
