server:
  port: 9000

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://postgres:5432/paystream
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
