server:
  port: 9000

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://postgres:5432/paystream
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionInitSql: "SET search_path TO account, public"


  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: account
    default-schema: account
    table: flyway_history_account
    create-schemas: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.default_schema: account


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: account-snapshot-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    org.springframework.kafka: INFO
    com.paystream.accountservice.infra.consumer: INFO
    root: INFO
    org.springframework.jdbc.core: DEBUG
    org.springframework.web: DEBUG
    com.paystream: DEBUG



