server:
  port: 8085

spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://postgres:5432/paystream   # <== DÜZELTİLDİ (postgres)
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    enabled: true
    table: flyway_history_transfer
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger-ui.html

ledger:
  base-url: http://ledger-service:9100
