server:
  port: 8085
  error:
    include-message: always
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp
      prefix: access_log
      pattern: '%h %l %u %t "%r" %s %b %D'

# core/transfer-service/src/main/resources/application-docker.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/paystream?currentSchema=public
  flyway:
    schemas: public
    default-schema: public
    table: flyway_history_transfer
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

redis:
  host: redis
  port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.paystream.transferservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,httpexchanges
  endpoint:
    health:
      show-details: always
      show-components: always
  httpexchanges:
    recording:
      enabled: true
