# core/transfer-service/src/main/resources/application-docker.yml
server:
  port: 8085
  error:
    include-message: always
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp
      prefix: access_log
      pattern: '%h %l %u %t "%r" %s %b %D'

spring:
  application:
    name: transfer-service

  datasource:
    # paystream-dev ağındaki Postgres container adı: ps-postgres
    url: jdbc:postgresql://ps-postgres:5432/paystream?currentSchema=public

  flyway:
    schemas: public
    default-schema: public
    table: flyway_history_transfer
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  cloud:
    loadbalancer:
      enabled: false  # discovery kullanmıyoruz

  kafka:
    # Kafka container adı: ps-kafka
    bootstrap-servers: ps-kafka:9092

eureka:
  client:
    serviceUrl:
      # Eureka container adı: ps-eureka
      defaultZone: ${EUREKA_URL:http://ps-eureka:8761/eureka}

ledger:
  # Ledger container adı: ps-ledger
  base-url: http://ps-ledger:9100

redis:
  # Redis container adı: ps-redis
  host: ps-redis
  port: 6379

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.paystream.transferservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,httpexchanges
  endpoint:
    health:
      show-details: always
      show-components: always
  httpexchanges:
    recording:
      enabled: true
