server:
  port: 9011

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

spring:
  kafka:
    bootstrap-servers: kafka:9092

weaviate:
  scheme: http
  host: weaviate
  port: 8080
