name: CI
on:
  push:
    branches: [ main, "feature/**", "fix/**", "chore/**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      # Windows'ta CRLF gelmiş olabilir; runner'da LF'e çevir + çalıştırılabilir yap
      - name: Fix Gradle wrapper (permissions & line endings)
        run: |
          sed -i 's/\r$//' gradlew || true
          chmod +x gradlew

      - name: Build & Test (monorepo)
        run: ./gradlew clean test build --no-daemon --stacktrace
