name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TESTCONTAINERS_RYUK_DISABLED: true
      TESTCONTAINERS_CHECKS_DISABLE: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew clean build --no-daemon --stacktrace

      - name: Build Docker image
        run: docker build -t paystream/transfer-service:ci -f core/transfer-service/Dockerfile .
