name: CI
on:
  push:
    branches: [ main, "feature/**", "fix/**", "chore/**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build & Test (monorepo)
        run: ./gradlew clean test build --no-daemon --stacktrace
