name: CI
on:
  push:
    branches: [ main, "feature/**", "fix/**", "chore/**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      # Windows'tan CRLF gelirse düzelt + izin ver
      - name: Prepare Gradle wrapper
        run: |
          sed -i 's/\r$//' gradlew || true
          chmod +x gradlew || true
          ls -l gradlew
          head -n 1 gradlew

      - name: Build & Test (monorepo)
        run: bash ./gradlew clean test build --no-daemon --stacktrace
