server:
  port: 9006

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paystream
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
redis:
  host: localhost
  port: 6379
